# Generated by Django 4.2.1 on 2023-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('is_door_open', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=0)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField(default=0)),
                ('elevators', models.ManyToManyField(to='elevator.elevator')),
            ],
        ),
    ]
